package com.futurecode.scarymonstercallchat.utils

enum class AppConstants {
    IS_NOTIFICATION_STARTS,
    NOTIFICATION_URL,

    ADMOB_BANNER,
    ADMOB_INTERSTITIAL,
    ADMOB_NATIVE,
    ADMOB_REWARD_AD,
    ADMOB_APP_OPEN,

    META_INTERSTITIAL,
    META_NATIVE,

    CLICK_LIMIT,
    CLICK_URL,
    CLICK_COUNT,

    PROMO_INDEX,

    AD_SHOW_COUNTER,
    AD_NETWORK_INDEX,
    NATIVE_AD_NETWORK_INDEX,
    NATIVE_BANNER_AD_NETWORK_INDEX,

    CUSTOM_URLS,

    AD_FREQUENCY,
    AD_FLOW,
    NATIVE_AD_FLOW,
    NATIVE_BANNER_AD_FLOW,

    ADS_OFF,
    CUSTOM_OFF,

    SHARE_MESSAGE,

    CONTACT_US,
    PRIVACY_POLICY,
    KEY_ONBOARDING_DONE,
    KEY_LANGAUGE,
    IS_SOUND_ENABLED,
    IS_VIBRATION_ENABLED,
    IS_FLASH_ENABLED,
    NOTIFICATION_KEY_INDEX,
    NotificationsList,
    PromosList

}